# TCL File Generated by Component Editor 17.1
# Tue Jun 12 19:38:05 CEST 2018
# DO NOT MODIFY


# 
# Avalon_interface_to_Smart_Meter_FSMs "Avalon Interface to FSMs" v1.0
#  2018.06.12.19:38:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Avalon_interface_to_Smart_Meter_FSMs
# 
set_module_property DESCRIPTION ""
set_module_property NAME Avalon_interface_to_Smart_Meter_FSMs
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP I/O
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon Interface to FSMs"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AVS_INTERFACE
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avs_interface.vhd VHDL PATH IP/avs_interface.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL AVS_INTERFACE
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avs_interface.vhd VHDL PATH IP/avs_interface.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset RESET_N reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 AVS_INTERFACE_ADDRESS address Input 3
add_interface_port avalon_slave_0 AVS_INTERFACE_READDATA readdata Output 8
add_interface_port avalon_slave_0 AVS_INTERFACE_WRITE write Input 1
add_interface_port avalon_slave_0 AVS_INTERFACE_WRITEDATA writedata Input 8
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point INTERFACE_TO_FSM
# 
add_interface INTERFACE_TO_FSM conduit end
set_interface_property INTERFACE_TO_FSM associatedClock clock
set_interface_property INTERFACE_TO_FSM associatedReset reset
set_interface_property INTERFACE_TO_FSM ENABLED true
set_interface_property INTERFACE_TO_FSM EXPORT_OF ""
set_interface_property INTERFACE_TO_FSM PORT_NAME_MAP ""
set_interface_property INTERFACE_TO_FSM CMSIS_SVD_VARIABLES ""
set_interface_property INTERFACE_TO_FSM SVD_ADDRESS_GROUP ""

add_interface_port INTERFACE_TO_FSM DATA_NEG_IN data_neg_in Input 8
add_interface_port INTERFACE_TO_FSM DATA_NEG_OUT data_neg_out Output 8
add_interface_port INTERFACE_TO_FSM DATA_POS_IN data_pos_in Input 8
add_interface_port INTERFACE_TO_FSM DATA_POS_OUT data_pos_out Output 8
add_interface_port INTERFACE_TO_FSM DATA_VALID_IN data_valid_in Input 1
add_interface_port INTERFACE_TO_FSM START_PUMPS start_pumps Output 1
add_interface_port INTERFACE_TO_FSM START_LOADS start_loads Output 1
add_interface_port INTERFACE_TO_FSM BATTERY battery Input 8

